var data = [
  {
    "companyId" :"58f0f98234b10f4366d92aaa",
    "references" : [],
    "projects" : [],
    "projectsApplication" : [],
     "products1": [{
        "productName": "",
        "technologyField": "",
        "productClass": "",
        "productCategory": "",
        "productSolution": "",
        "businessObjective": "",
        "problemSolved": "",
        "applicationIndustry": "",
        "applicationSector":"",
        "applicationSubSector":"",
        "applicationValueChain": "",
        "applicationBusinessType": "",
        "applicationKeyActivities": "",
        "applicationKeyResources": "",
        "applicationCostStructure": "",
        "digitilizationScope": "",
        "applicationValueProposition": "",
        "uniqueSellingPoints": "",
        "productTechnologies": "",
        "compatibileTechnologies": "",
        "requirements": "",
        "patents": "",
        "pricingIndicationMin": "",
        "pricingIndicationMax": "",
        "capacityIndication": "",
        "delivery": "",
        "integration": "",
        "maintenance": "",
        "geographicalMarkets": "",
        "industryStandards": "",
        "dataSecurity": "",
        "segmentsDescription": "",
        "regulatoryCondition": "",
        "productRisk": "",
        "otherProductAttributes": ""
    }],
    "products2": [{
        "productName": "",
        "technologyField": "",
        "productClass": "",
        "productCategory": "",
        "productSolution": "",
        "businessObjective": "",
        "problemSolved": "",
        "applicationIndustry": "",
        "applicationSector":"",
        "applicationSubSector":"",
        "applicationValueChain": "",
        "applicationBusinessType": "",
        "applicationKeyActivities": "",
        "applicationKeyResources": "",
        "applicationCostStructure": "",
        "digitilizationScope": "",
        "applicationValueProposition": "",
        "uniqueSellingPoints": "",
        "productTechnologies": "",
        "compatibileTechnologies": "",
        "requirements": "",
        "patents": "",
        "pricingIndicationMin": "",
        "pricingIndicationMax": "",
        "capacityIndication": "",
        "delivery": "",
        "integration": "",
        "maintenance": "",
        "geographicalMarkets": "",
        "industryStandards": "",
        "dataSecurity": "",
        "segmentsDescription": "",
        "regulatoryCondition": "",
        "productRisk": "",
        "otherProductAttributes": ""
    }],
    "otherWebPresense" : "",
    "twitter" : "",
    "linkedIn" : "",
    "facebook" : "",
    "skype" : "",
    "companyEmail" : "",
    "phone" : "",
    "companyWebsite" : "",
    "investors_list": "",
    "supportFunction": {
      "supportFunctions": "",
      "supportFunctionLevel": ""
    },
    "valueChain" : {
      "valueChainPosition": "",
      "valueChainLevel": ""
    },
    "totalFundingObtain" : "",
    "investmentStage" : "",
    "revenue" : "",
    "standardsCertifications" : "",
    "technologies" : "",
    "revenueStreams" : "",
    "channels" : "",
    "customerSegments" : "",
    "valueProposition" : "",
    "costStructure" : "",
    "keyPartnership" : "",
    "keyResources" : "",
    "keyActivities" : "",
    "otherBusinessRelationships" : {
      "otherBusinessRelationshipsName": "",
      "otherBusinessRelationshipsType" : ""
    },
    "holdingCompanies" : "",
    "daughterCompanies" : "",
    "suppliers" : "",
    "investors" : "",
    "strategicPartners" : "",
    "customers" : "",
    "teamMember" : {
      "teamMemberPosition": "",
      "teamMemberName" : ""
    },
    "othercompanyAttributes" : "",
    "companyCulture" : "",
    "vision" :  "",
    "mission" : "",
    "ftes" : "",
    "languages" : "",
    "yearEstablished" : "",
    "streetAddress" : "",
    "zipCode" : "",
    "locations" : "",
    "country" : "",
    "headquarters" : "",
    "subSector" : "",
    "profileTraction": "",
    "statusLive":"",
    "sector" : "",
    "industry" : "",
    "legalForm" : "",
    "businessType" : "",
    "organizationType" : "",
    "companyDescription" : "",
    "slogan" : "",
    "companyName" :"",
    "logoURI" : "",
    "profileUpdatedBy" : "",
    "profileCreatedBy" : "",
    "passiveProfileSource" : "",
    "companyStatus" : "Passive",
    "useCase" : "",
    "createdAt":"",
    "updatedAt":"",
    "__v" : 0
}
]


module.exports = {data}

